ruby/parameter-binding/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'pages#home'
  resources :pages,  except:  [:index]
end

ruby/parameter-binding/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

ruby/parameter-binding/app/models/user.rb
class User < ApplicationRecord
end

ruby/parameter-binding/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

ruby/parameter-binding/app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home
        @user = User.all
      end

      def show
        @user = User.find(params[:id])
      end

      def edit
        @user = User.find(params[:id])
      end
    
      def update
        @user = User.find(params[:id])
        @user.update(user_params)
        redirect_to root_path
      end

      private
      def user_params
        params.require(:user).permit!
      end
end

ruby/parameter-binding/app/helpers/application_helper.rb
module ApplicationHelper
end

ruby/parameter-binding/app/helpers/pages_helper.rb
module PagesHelper
end

ruby/parameter-binding/app/helpers/tasks_helper.rb
module TasksHelper
end

ruby/parameter-binding/app/views/layouts/application.html.erb
    
<!DOCTYPE html>
<html>
<head>

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Live demonstrations</title>

<script src="/static/js/lumino.glyphs.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

ruby/parameter-binding/app/views/pages/edit.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container-fluid">
    <div class="navbar-header"> 
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <ul class="user-menu">
            <li class="dropdown pull-right">

                <ul class="dropdown-menu" role="menu">
                </ul>
            </li>
        </ul>
    </div>
</div><!-- /.container-fluid -->
</nav>

<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
<br/><br/>
<center>
<%= image_tag("logo.svg", :alt => "SKF logo") %>
<br/>
<p style="color:#515594; font-size:1.0em;"><a href="https://github.com/blabla1337/skf-flask" style="color:#515594; font-size:1.7em;">OWASP S.K.F.</a></p>  	 			<p><a href="https://gitter.im/Security-Knowledge-Framework/Lobby" rel="nofollow"> <%= image_tag("badge.svg", :alt => "rss feed") %> </a> 			</p> 
</center>
</div><!--/.sidebar-->

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">			
<div class="row">

</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Live demonstration!</h1>
    </div>
</div><!--/.row-->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Parameter binding on Rails!</div>
            <div class="panel-body">
                <div class="col-md-6">
                <h3>Update user Details</h3>
                <%= form_with model: @user,  :url => {:action => :update}, method: :patch do |form| %>
                    <input type="hidden" name="_method" value="patch" />
                    <%= form.text_field :username, class: "form-control", value: @user.username %>
                    <%= form.text_field :title, class: "form-control", value: @user.title %>
                    <br/>
                <%= form.submit class:"btn btn-success"%>
                <%= link_to 'Go back', root_path, class: "btn btn-primary"%>

                <% end %>     

            </div>
        </div>
    </div><!-- /.col-->
</div><!-- /.row -->

</div><!--/.main-->

ruby/parameter-binding/app/views/pages/home.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
<div class="container-fluid">
    <div class="navbar-header"> 
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#sidebar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <ul class="user-menu">
            <li class="dropdown pull-right">

                <ul class="dropdown-menu" role="menu">
                </ul>
            </li>
        </ul>
    </div>
</div><!-- /.container-fluid -->
</nav>

<div id="sidebar-collapse" class="col-sm-3 col-lg-2 sidebar">
<br/><br/>
<center>
<%= image_tag("logo.svg", :alt => "SKF logo") %>
<br/>
<p style="color:#515594; font-size:1.0em;"><a href="https://github.com/blabla1337/skf-flask" style="color:#515594; font-size:1.7em;">OWASP S.K.F.</a></p>  	 			<p><a href="https://gitter.im/Security-Knowledge-Framework/Lobby" rel="nofollow"> <%= image_tag("badge.svg", :alt => "rss feed") %> </a> 			</p> 
</center>
</div><!--/.sidebar-->

<div class="col-sm-9 col-sm-offset-3 col-lg-10 col-lg-offset-2 main">			
<div class="row">

</div><!--/.row-->

<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header">Live demonstration!</h1>
    </div>
</div><!--/.row-->
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">Parameter binding on Rails!</div>
            <div class="panel-body">
                <div class="col-md-6">
                <% if @user.empty? %>
                  <p>foobar</p>
                <% else %> 
                <div class="table-responsive">
                  <table class="table table-striped table-bordered table-hover">
                  <thead>
                    <tr>
                        <th>User</th>
                        <th>Title</th>
                        <th>Privileged</th>
                    </tr>
                  </thead>
                    <tbody>
                <% @user.each do |user| %>     
                            <tr>
                                <td> <%= link_to user.username, edit_page_path(user) %></td>
                                <td> <%= user.title %></td>
                                <td> <%= user.is_admin %> </td>
                            </tr>
                    <% end %>
                    </tbody>
                    </table>
                </div>
                <% end %>
                
            </div>
        </div>
    </div><!-- /.col-->
</div><!-- /.row -->

</div><!--/.main-->